import { Roboto } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


const roboto = Roboto({
  weight: "400",       
  subsets: ["latin"],
  variable: "--font-roboto",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
